name: python-unit-test
run-name: Evaluating ${{ github.actor }} code push
on: [push]
jobs:
  test-branch:
    strategy:
      matrix:
        python-version:  3.11
        os: [ubuntu-22.04, windows-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Running pytest
        run: pytest